### PR TITLE
Fix to support cross-schema foreign keys in postgesql

### LINKED ISSUE #137: Why am I getting this? Error: error scanning foreign key constraint: sql: Scan error on column index 5, name "table_name": converting NULL to string is unsupported
I have found Gnorm very helpful for generating code that creates a webserver that connects to a gRPC server that connects to postgres. I use Gnorm to generate proto files, go db code, go web server code, and html templates and saved a LOT of time. I finished the first version of my project 6 months ago, but now have a number of db changes and need to update. 

I am getting a strange error when I run gnorm gen -c myconfig.toml:

> Error: error scanning foreign key constraint: sql: Scan error on column index 5, name "table_name": converting NULL to string is unsupported

I am assuming that table_name is coming from information.schema, since nothing in my schema has that name.

I haven't changed my gnorm config files or template files since the last successful build. My db colleague has updated a few fields and created new tables in my schema as well as adding new schemas in the same postgres instance. However, I do specify only the schema I want in the config:
DBType = "postgres"
Schemas = ["stsdb"]

Is it possible that Gnorm is getting confused by information.schema or changes in other schemas?

### PR DESCRIPTION
**Pull request by saward**
Changed the query to use the schema for the foreign key itself, and not the schema for the current table.  Resolves #137.

It was a few months ago I tested this, but I'm quite sure the above is what was going on.  Have been using this issue for a production project for a few months, and haven't encountered any side effects.

### CODE REVIEW

**Comment by saward** [comment]
@natefinch Could you please merge this in?  It's a bit troublesome for me to use my local version with this fix.  Thanks!

**Comment by saward** [comment]
@natefinch Any chance you could hit the merge button for this patch please?

**Comment by saward** [comment]
@natefinch Hi Nate, is it possible you could hit merge on this please?

**Comment by natefinch** [comment]
Done! :)

**Comment by saward** [comment]
Excellent, thanks!

**Pull request merged**
