### PR TITLE
fix '$' replacement , passwords may contains '' or '$'

### PR DESCRIPTION
**Pull request by ahmdrz**

### CODE REVIEW

**Comment by natefinch** [comment]
I think most people will prefer to not have their password in the configuration file.  However, what I think we can do is add another config value that'll tell gnorm not to expand environment variables in the connection string.

**Comment by ahmdrz** [comment]
Hi @natefinch , 
1. I think we can encrypt config file , when we want to load file , enter password key to decrypt and use file as config.
2. Your idea is great , But which one is important ? How many users use environment variables as config ?

So , I want to contribute your code :smile: , What can I do ?

File encryption or new config option ?

**Comment by natefinch** [comment]
I think a lot of people tend to use environment variables, especially for passwords, but it obviously depends on the person.  I don't think many people will want their whole config file encrypted, because most of it is not sensitive information at all.

If you'd like to contribute, a you can add a new config value called 

ExpandConnStr 

Make it a boolean, make it default to true if not explicitly set in the config file.  

After you get it working, add it to gnorm/cli/gnorm.toml with an explanation of what it does in the comment above it, and then run `go generate ./...` from the gnorm directory, which will update some of the docs from that gnorm.toml file.

**Comment by ahmdrz** [comment]
Of course
As soon as possible

Regards.

On Oct 23, 2017 17:49, Nate Finch <notifications@github.com> wrote:

I think a lot of people tend to use environment variables, especially for passwords, but it obviously depends on the person. I don't think many people will want their whole config file encrypted, because most of it is not sensitive information at all.

If you'd like to contribute, a you can add a new config value called

ExpandConnStr

Make it a boolean, make it default to true if not explicitly set in the config file.

After you get it working, add it to gnorm/cli/gnorm.toml with an explanation of what it does in the comment above it, and then run go generate ./... from the gnorm directory, which will update some of the docs from that gnorm.toml file.

**Comment by natefinch** [comment]
Closing, looking forward to the new PR. Thanks!

**Pull request closed without merging**
